//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by registrator.rc
//
#define IDS_APPNAME                     1
#define IDS_DESCRIPTION                 2
#define IDI_APPICON                     101
#define IDB_BITMAP1                     102
#define IDB_BITMAP2                     103
#define IDC_CURSOR1                     104
#define IDB_BITMAP3                     106
#define IDD_DIALOG_ABOUT                107
#define IDM_EXIT                        1000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        108
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
